### ISSUE TITLE
如何使用gpu进行版面分析

### ISSUE THREAD

**Issue by JingyiWang3** [RapidAI/RapidStructure#1]
How to use gpu for inference?

**Comment by SWHL** [comment]
- 这个需要用到onnxruntime-gpu版来推理模型，具体操作可以参考这里：[onnxruntime gpu版推理](https://github.com/RapidAI/RapidOCR/wiki/onnxruntime-gpu%E7%89%88%E6%8E%A8%E7%90%86)
- 不过，onnxruntime-gpu版，针对输入图像尺寸一直变化时，推理速度比CPU版要慢很多

**Comment by SWHL** [comment]
issue先关闭了，后续有问题可以再开
