### ISSUE TITLE
文档错误 # bbox: [左上角x0,左上角y0, 右下角x0, 右上角x1]

### ISSUE THREAD

**Issue by qqeip** [RapidAI/RapidStructure#9]
文档错误 # bbox: [左上角x0,左上角y0, 右下角x0, 右上角x1]
应该是 # bbox: [左上角x0,左上角y0, 右下角x1, 右下角y1]
https://github.com/RapidAI/RapidStructure/blob/main/docs/README_Layout.md

**Comment by SWHL** [comment]
感谢指正，问题已经修复。
